### ISSUE TITLE
Unable to expand routes

### ISSUE THREAD

**Issue by sonicalabs** [sebastienheyd/boilerplate#12]
Hi Sebastien,

After update 5.4 branch to 5.8, I'm unable to expand routes to add functionality to boilerplate. Maybe u can help me with this strange behaivour

I Added boilerplate.php to root route folder and add some route example closure

`Route::get('testroute', function (){
    return 'I'm a test route';
})->name('routetest');`

At this point laravel don't load boilerplate.php file so added file to route provider App/Providers/RouteServiceProvider.php

`public function map()
{
$this->mapApiRoutes();
$this->mapWebRoutes();
$this->mapAdminRoutes();
}`

`protected function mapAdminRoutes()
    {
        Route::middleware('web')
            ->namespace('\App\Http\Controllers\Admin')
            ->group(base_path('routes/admin.php'));
    }`

if I check routes in console with php artisan route:list, new route appears on list as a closure.. all seems to work fine but if a try the url in browser 

http://domain.tld/testroute

always returns a 404 error page. Only happens with new routes added outside boilerplate scope, if I try to get p.e users page

http://domain.tld/users works as expected and returns users dashboard page.

How do you expand routes in your package?? In old version was so easy, but after update I'm getting crazy about this

thanks in advance

**Comment by sebastienheyd** [comment]
Hi,

Boilerplate's original routes must not be overloaded anymore, this is why `boilerplate.php` is no more used in `routes` folder.

I think your problem is not a boilerplate problem but a Laravel routing problem.

What do you have in `routes/admin.php` ? You have an empty prefix in `config/boilerplate/app.php` ?

You have an exemple on how I add routes to boilerplate in [one of my other packages](https://github.com/sebastienheyd/boilerplate-media-manager/blob/master/src/routes/boilerplate-media-manager.php)

**Comment by sonicalabs** [comment]
Hi, Finally I found the cause of 404.

When I map the extra route file, just added at the end of the chain and this cause web.php routes loaded before admin.php routes. One of the web.php route cause this 404.

Now, I change the chain order, and put admin.php route first and all is working as expected.

`public function map() { $this->mapAdminRoutes(); $this->mapApiRoutes(); $this->mapWebRoutes();  }`

Useful if someone have the same issue. 

Regards,
Daniel
