### ISSUE TITLE
How to publish views ?

### ISSUE THREAD

**Issue by DonDiegoAA** [sebastienheyd/boilerplate#15]
Hi,

The doc says:

2. Run the command below to publish assets, views, lang files, ...
`php artisan vendor:publish --provider="Sebastienheyd\Boilerplate\BoilerplateServiceProvider"`

But I don't see boilerplate views in ressources. Is there a way to publish views ?

Thank you

**Comment by DonDiegoAA** [comment]
Ok, I just had to copy the vendor\sebastienheyd\boilerplate\src\resources\views folder into resources\views\vendor\boilerplate

Sorry for the silly question.
Is there a reason why publish does not do this by default ?

**Comment by sebastienheyd** [comment]
Hi,

At the beginning of the development the package published the views, then I realized that it didn't have to be modified.

The solution of publishing them manually is largely sufficient, because it is necessary only in very specific cases. Too bad, however, that Laraval does not allow you to select what you publish, it would be useful to be able to publish only the views if necessary.
