### ISSUE TITLE
Extract models, controllers and routes

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#35]
Is there a way to extract models, controllers and routes in vendor folder as views? I need to make some changes. Do you have fresh installation where this package is integrated?

**Comment by sebastienheyd** [comment]
For the moment there is no command to automate these extracts and overloads.

However, to modify the routes, you can redefine those of the package by overwriting them. To do so, you just have to add them in the `routes/web.php` file

From there you can define your own controllers to call, example :

```php
$default = [
    'prefix'     => config('boilerplate.app.prefix', ''),
    'domain'     => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplatelocale'],
    'as'         => 'boilerplate.',
];

Route::group($default, function () {
    Route::group(['middleware' => ['boilerplateauth', 'ability:admin,backend_access']], function () {
        Route::get('/', ['as' => 'dashboard', 'uses' => 'App\Http\Controllers\MyOwnDashboardController@index']);
    });
    
    Route::get('login', ['as' => 'login', 'uses' => 'App\Http\Controllers\LoginController@showLoginForm']);
});
```

This will use `App\Http\Controllers\MyOwnDashboardController` and `App\Http\Controllers\LoginController` controllers instead of the package controllers. With this you can redefine any route and controller used by your application.

For the models, create your own by extending those of the package then declare them in `config/boilerplate/laratrust.php` and `config/boilerplate/auth.php`

I will see if I can create a command to make this easier.
