### ISSUE TITLE
[Feature request]Dark mode button

### ISSUE THREAD

**Issue by Novocaine85** [sebastienheyd/boilerplate#41]
Hey @sebastienheyd! Thank you for your work. Is really awesome.

Would be possible to add the dark mode button on the top navbar as in adminlte 3.1?

The css is already compiled for it. Just append class dark-mode to body and the magic is done.

![image](https://user-images.githubusercontent.com/7164237/132967429-8a6d87d3-9dcf-4ec9-b13a-c0d68653c1ee.png)

thank you!

**Comment by sebastienheyd** [comment]
Hey @Novocaine85 , thanks for your support !

I've just added the dark mode to the [release 7.7.0](https://github.com/sebastienheyd/boilerplate/releases/tag/7.7.0) (read the release notes)

I had to add a `settings` field to the `users` table in order to keep the setting for each user. I had already intended to do this earlier, this was the opportunity to develop it.

I also had to modify the call to TinyMCE to reload it in dark mode.
