### ISSUE TITLE
Datatable buttons are not working

### ISSUE THREAD

**Issue by lawsjas** [sebastienheyd/boilerplate#46]
I am having an issue with Datatables where I am not able to add copy, excel, pdf buttons.

I've tried changing the dom to:
dom: 'Bfrtip',
    buttons: [
        'copy', 'excel', 'pdf'
    ]

The css of the datatables are messed up and no buttons are displaying.

My blade code
![image](https://user-images.githubusercontent.com/65940936/143599095-81a23ab7-e062-462a-8a6f-8f1e801e319d.png)

My preview
![image](https://user-images.githubusercontent.com/65940936/143599163-4baf5f85-56ac-403f-9e53-39df42f0d4e8.png)

**Comment by sebastienheyd** [comment]
This happens because DataTables is used with Bootstrap 4.

https://datatables.net/extensions/buttons/examples/styling/bootstrap4

You also need to load some additional scripts after `@include('boilerplate::load.datatables', ['buttons' => true])` to make `buttons`work :

```blade
@push('plugin-js')
<script src="{!! mix('/plugins/datatables/plugins/'.$plugin.'.bootstrap4.min.js', '/assets/vendor/boilerplate') !!}"></script>
@endpush
```

I will add these features to the blade component `<x-boilerplate::datatable>` : https://sebastienheyd.github.io/boilerplate/components/datatable

**Comment by sebastienheyd** [comment]
I've just added the `buttons` feature to the datatable component with the release [7.10.4](https://github.com/sebastienheyd/boilerplate/releases/tag/7.10.4)

I strongly encourage you to use the datatable generator : https://sebastienheyd.github.io/boilerplate/datatables/create

You can also see a real example because the generator has been used for the users list : https://github.com/sebastienheyd/boilerplate/blob/master/src/Datatables/UsersDatatable.php
