### ISSUE TITLE
Cannot load images and insecure forms

### ISSUE THREAD

**Issue by x-bet** [sebastienheyd/boilerplate#47]
Hi,

First of all, thanks for your `boilerplate` it's an incredible help for all devs.
I would like to know if I did something wrong, or I discovered some issues. Essentially:

1) I have installed the `boilerplate` and when I login I have this info message:

![domain](https://user-images.githubusercontent.com/91073169/148640721-602bc571-5bbf-4855-9c55-45d000a53c36.jpg)

>The information you are about to send is not secure
As this form was submitted via an insecure connection, the information will be visible to others.

within `src/.env` I have this configuration: `APP_URL=https://example.com` (hide the url for privacy reason), and the ssl is correctly registered. This also happen when I logout.

2) When I upload an avatar, it always return 404 (even using gravatar):

![Immagine 2022-01-08 111934](https://user-images.githubusercontent.com/91073169/148640750-6c45cebc-a21e-4807-8d1e-fc95b0df7225.jpg)

This happen only for `public/images/avatars`, the problem isn't showing for `public/assets`, check also:

![Immagine 2022-01-08 111856](https://user-images.githubusercontent.com/91073169/148640827-da9fa987-db62-4754-90d7-cdeedfaab74e.jpg)

Is there something I can do to fix this?

Thanks in advance

**Comment by x-bet** [comment]
@sebastienheyd 

Found the issue, you set 0766 on `getAvatarFromGravatar()` but should be: 0755. Also, for the ssl, the Laravel Form component returns http: instead of https: even if I'm using https, so must be a problem on Laravel side.
Some users has suggested to use: `\URL::forceScheme('https');` within `AppServiceProvider`

**Comment by sebastienheyd** [comment]
Hi,

Thanks for your support!

Can you tell me which operating system and which web server you are using? Are you behind a proxy or reverse proxy?

For getAvatarFromGravatar(), this can't be 0755 because this is Read/Execute permissions for group and others, instead of Read/Write (0766). To enable avatar image to be written this must be 0766.

If you are using Laravel behind a load balancer or other proxy, `Request::isSecure()` that will be used to define https for forms will always return false, unless you trust the `X-Forwarded-Proto` header from your proxy server.
