### ISSUE TITLE
Question: I am not clear about the Menu

### ISSUE THREAD

**Issue by verygod** [sebastienheyd/boilerplate#5]
Hello, I'm fairly new to Laravel and your CRM example is really nice for my playground, but I can't seem to understand the Menu part. Those "User" and "Logs" files don't generate after project setup, as the whole Menu folder. I can see the config tho. The authors way with middleware dose work. But I'm not clear about your way - I can't seem to find any place where I could edit the whole Menu ir create a new one.

Plus: Permission CRUD setup would be great if it was out of the box :)

**EDIT** If you edit the menus in the Vendor it dose work, for now I could stick to that.

**Comment by sebastienheyd** [comment]
Hello,

There is not a single place to edit the whole menu. I chose to split the menu into several files so that I could provide them in other packages.

For exemple, to add new menu items I create a new folder `app/Menu`. Into this folder i put classes to add menu items, for exemple Shops.php (see the comments) :

```php
<?php

namespace App\Menu;

use Sebastienheyd\Boilerplate\Menu\Builder;

class Shops
{
    public function make(Builder $menu)
    {
        // You must have a route with the alias shops.index
        // See font-awesome for icons, here fa-shopping-cart
        $menu->add('Shops', [ 'route' => 'shops.index', 'icon' => 'shopping-cart' ])
            ->id('shops')      // Menu item ID
            ->order(100)     // This will manage the menu item "weight" to define his position
            ->activeIfRoute('shops.*');  // To set "active" css class on the menu item for all pages with route beginning with "shops."
    }
}
```

After that, you need to declare it into `config/boilerplate/menu.php` : 

```php
<?php

/**
 * Define here every class you want to call to build the backend menu
 * Every class need a method make(Builder $menu)
 *
 * @see \Sebastienheyd\Boilerplate\ViewComposers\MenuComposer
 */

return [
    'providers' => [
        \Sebastienheyd\Boilerplate\Menu\Users::class,
        \Sebastienheyd\Boilerplate\Menu\Logs::class,
        \App\Menu\Shops::class,
    ]
];
```

By doing this, you can deliver the file in a package and for example install it by making a `vendor:publish` . The only condition is that you must add the line into `config/boilerplate/menu.php` (I'm thinking on how i can do it magically).

You can watch in [Users.php](https://raw.githubusercontent.com/sebastienheyd/boilerplate/5.6/src/Menu/Users.php) for adding sub items.

Permissions are linked to scripts, views, routes, ... this is why I use migrations and i'm not allowing to create them by a form... for this moment... ;)

**Comment by verygod** [comment]
Perfect! Got it this time! Menu is up and running now, will wait for the permissions update. The option to CRUD the permission would be cool, the whole back-end stuff could be taken care of by the dev himself. Atleast when I search for something like you did was simple. Easy code (which most of the part is in your code) and the CRUD options for user / role / permission managment. I can code everything else myself just the forms take way longer than I want to. :D 

Thanks for the explanation. :)
