### ISSUE TITLE
Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#50]
Hi,

I have created a migration like this:

```
Schema::create('riskareas_fields', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->enum('type', ['number', 'min_max', 'text']);
    $table->string('icon')->nullable();
    $table->timestamps();
    $table->softDeletes();
});
```
then I've defined the model

```
class RiskareasField extends Model
{
    protected $table = "riskareas_fields";
    protected $fillable = [
        'name',
        'type',
        'icon'
    ];
}
```

I tried to create a datatable using the boilerplate command: `php artisan boilerplate:datatable riskareasfields --model="App\Models\RiskareasField` but I get:

>Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

I'm using Laravel 8 and php 8.0.2

**Comment by sebastienheyd** [comment]
Hi,

`enum` is not supported by Doctrine, and I use Doctrine to get the field name and type to set the correct type and filter to use.

You can use the `--nodb` option when calling the artisan command or set `string` type instead of `enum`, see [the documentation](https://sebastienheyd.github.io/boilerplate/datatables/create) to avoid using Doctrine.

I must see if I can avoid the exception and setting a default type when meeting an `enum`

**Comment by cod3rshotout** [comment]
Thanks
