### ISSUE TITLE
[enhancement] Add height property to tinymce

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#68]
Would be possible to include the height property to tinymce component?

**Comment by sebastienheyd** [comment]
Fixed in 7.16.1

Due to the `autoresize` plugin, instead of `height` I added `min-height` and `max-height`.

If you want to set a fixed height just set `min-height` and `max-height` with the same value.

[See TinyMCE component documentation](https://sebastienheyd.github.io/boilerplate/components/tinymce)

**Comment by cod3rshotout** [comment]
@sebastienheyd I tried:  <x-boilerplate::tinymce name="content" label="sections.content" :min-height="800" /> but nothing change

**Comment by sebastienheyd** [comment]
You don't need to add ":" before min-height but this is not the problem.

If you have used `boilerplate:scaffold` in your projet you have to replace or delete the view `resources/views/vendor/boilerplate/components/select2.blade.php`

I don't recommend using scaffold because you don't get the benefit of updates.
